"""Adapter that uses a trained routing student for mode probabilities."""

from __future__ import annotations

import json
import pickle
from pathlib import Path
from typing import Any

from vao.agents.base import AgentState
from vao.agents.local_stub_adapter import LocalStubAdapter
from vao.schemas import ModeDistribution
from vao.taxonomy import MODES, normalize_mode_probs
from vao.training.routing_features import DEFAULT_MAX_SOURCE_CHARS, state_to_text


class RoutingStudentAdapter(LocalStubAdapter):
    """Student router with deterministic local-stub candidate edits.

    This keeps online experiments cheap and isolates the routing-only variable:
    the six branch candidate implementations are generated by the existing
    deterministic local stub, while q_t comes from the trained routing student.
    """

    def __init__(
        self,
        model_id: str = "routing-student-v1",
        *,
        model_path: str = "training/phase5_routing_student/model.pkl",
        max_source_chars: int = DEFAULT_MAX_SOURCE_CHARS,
        **kwargs: object,
    ) -> None:
        super().__init__(model_id=model_id, **kwargs)
        self.model_path = Path(model_path)
        self.max_source_chars = int(max_source_chars)
        self._payload: dict[str, Any] | None = None

    def propose_mode_distribution(self, state: AgentState) -> ModeDistribution:
        payload = self._load_payload()
        text = state_to_text(state, max_source_chars=self.max_source_chars)
        model = payload["model"]
        if hasattr(model, "predict_proba"):
            probs_raw = model.predict_proba([text])[0]
            classes = [str(item) for item in model.classes_]
            probs = {mode: 0.0 for mode in MODES}
            for label, probability in zip(classes, probs_raw, strict=True):
                if label in probs:
                    probs[label] = float(probability)
        else:
            top = str(model.predict([text])[0])
            probs = {mode: 1.0 if mode == top else 0.0 for mode in MODES}
        probs = normalize_mode_probs(probs)
        ranking = sorted(MODES, key=lambda mode: probs[mode], reverse=True)
        parsed = {
            "mode_probs": probs,
            "mode_ranking": ranking,
            "mode_rationales": {
                mode: "Routing-student probability from offline supervised checkpoint."
                for mode in MODES
            },
            "student_model_path": str(self.model_path),
            "student_train_summary": payload.get("train_summary", {}),
        }
        raw = json.dumps(parsed, sort_keys=True)
        return ModeDistribution(raw_text=raw, parsed_json=parsed, **parsed)

    def _load_payload(self) -> dict[str, Any]:
        if self._payload is None:
            with self.model_path.open("rb") as handle:
                self._payload = pickle.load(handle)
        return self._payload
